CREATE DATABASE DB_2PI;

USE DB_2PI;

CREATE TABLE IF NOT EXISTS TB_CEP(
    ID_CEP INT PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR(8),
    RUA VARCHAR(100),
    NUMERO VARCHAR(4),
    COMP VARCHAR(50),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    UF VARCHAR(2) 
);